//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site_priprema.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuID { get; set; }
        public string Menu1 { get; set; }
        public string Link { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
    
        public virtual Menu Menus1 { get; set; }
        public virtual Menu Menu2 { get; set; }
    }
}
